-- 코드를 입력하세요
SELECT  BOOK_ID, AUTHOR_NAME, TO_CHAR(BK.PUBLISHED_DATE, 'YYYY-MM-DD') PUBHLISHED_DATE
FROM    BOOK BK
LEFT JOIN AUTHOR AT ON BK.AUTHOR_ID = AT.AUTHOR_ID
WHERE   BK.CATEGORY ='경제'
ORDER BY PUBLISHED_DATE
;