SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, to_char(B.CREATED_DATE, 'yyyy-mm-dd') created_date 
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID AND A.CREATED_DATE BETWEEN TO_DATE('2022-10-01','yyyy-mm-dd') AND TO_DATE('2022-10-31','yyyy-mm-dd')
ORDER BY B.CREATED_DATE, A.TITLE;